2023-02-28 11:15:46,730 ERROR: Exception on / [GET] [in D:\Esthenos\Learn\venv\lib\site-packages\flask\app.py:1744]
Traceback (most recent call last):
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "D:\Esthenos\Learn\app\routes.py", line 22, in index
    return render_template("index.html", title='Home Page', posts=posts, form=form)
NameError: name 'posts' is not defined
2023-02-28 11:16:23,237 INFO: Microblog startup [in D:\Esthenos\Learn\app\__init__.py:44]
2023-02-28 11:16:30,718 ERROR: Exception on / [GET] [in D:\Esthenos\Learn\venv\lib\site-packages\flask\app.py:1744]
Traceback (most recent call last):
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "D:\Esthenos\Learn\app\routes.py", line 22, in index
    return render_template("index.html", title='Home Page', form=form)
NameError: name 'form' is not defined
2023-02-28 11:16:40,205 ERROR: Exception on /index [GET] [in D:\Esthenos\Learn\venv\lib\site-packages\flask\app.py:1744]
Traceback (most recent call last):
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "D:\Esthenos\Learn\app\routes.py", line 22, in index
    return render_template("index.html", title='Home Page', form=form)
NameError: name 'form' is not defined
2023-02-28 11:18:02,561 INFO: Microblog startup [in D:\Esthenos\Learn\app\__init__.py:44]
2023-02-28 11:18:18,092 ERROR: Exception on /user/ab [GET] [in D:\Esthenos\Learn\venv\lib\site-packages\flask\app.py:1744]
Traceback (most recent call last):
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "D:\Esthenos\Learn\app\routes.py", line 32, in user
    return render_template('user.html', user=user, posts=posts)
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "D:\Esthenos\Learn\venv\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "D:\Esthenos\Learn\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\Esthenos\Learn\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\Esthenos\Learn\app\templates\base.html", line 40, in top-level template code
    {% block content %}{% endblock %}
  File "D:\Esthenos\Learn\app\templates\user.html", line 18, in block 'content'
    {{ form.hidden_tag() }}
  File "D:\Esthenos\Learn\venv\lib\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2023-02-28 11:19:07,415 INFO: Microblog startup [in D:\Esthenos\Learn\app\__init__.py:44]
2023-02-28 11:19:30,147 ERROR: Exception on /user/ab [GET] [in D:\Esthenos\Learn\venv\lib\site-packages\flask\app.py:1744]
Traceback (most recent call last):
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "D:\Esthenos\Learn\app\routes.py", line 32, in user
    return render_template('user.html', user=user, posts=posts)
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "D:\Esthenos\Learn\venv\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "D:\Esthenos\Learn\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\Esthenos\Learn\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\Esthenos\Learn\app\templates\base.html", line 40, in top-level template code
    {% block content %}{% endblock %}
  File "D:\Esthenos\Learn\app\templates\user.html", line 18, in block 'content'
    {{ form.hidden_tag() }}
  File "D:\Esthenos\Learn\venv\lib\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2023-02-28 11:32:07,175 INFO: Microblog startup [in D:\Esthenos\Learn\app\__init__.py:44]
