2023-02-27 16:08:04,781 INFO: Microblog startup [in D:\Esthenos\Learn\app\__init__.py:44]
2023-02-27 16:08:15,809 INFO: Microblog startup [in D:\Esthenos\Learn\app\__init__.py:44]
2023-02-27 17:00:25,456 INFO: Microblog startup [in D:\Esthenos\Learn\app\__init__.py:44]
2023-02-27 17:08:46,051 INFO: Microblog startup [in D:\Esthenos\Learn\app\__init__.py:44]
2023-02-28 11:06:18,387 INFO: Microblog startup [in D:\Esthenos\Learn\app\__init__.py:44]
2023-02-28 11:06:27,023 INFO: Microblog startup [in D:\Esthenos\Learn\app\__init__.py:44]
2023-02-28 11:07:24,153 ERROR: Exception on /user/hd [GET] [in D:\Esthenos\Learn\venv\lib\site-packages\flask\app.py:1744]
Traceback (most recent call last):
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "D:\Esthenos\Learn\app\routes.py", line 31, in user
    return render_template('user.html', user=user, posts=posts)
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "D:\Esthenos\Learn\venv\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "D:\Esthenos\Learn\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\Esthenos\Learn\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\Esthenos\Learn\app\templates\base.html", line 40, in top-level template code
    {% block content %}{% endblock %}
  File "D:\Esthenos\Learn\app\templates\user.html", line 18, in block 'content'
    {{ form.hidden_tag() }}
  File "D:\Esthenos\Learn\venv\lib\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2023-02-28 11:08:35,769 ERROR: Exception on /user/ab [GET] [in D:\Esthenos\Learn\venv\lib\site-packages\flask\app.py:1744]
Traceback (most recent call last):
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "D:\Esthenos\Learn\app\routes.py", line 31, in user
    return render_template('user.html', user=user, posts=posts)
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "D:\Esthenos\Learn\venv\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "D:\Esthenos\Learn\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\Esthenos\Learn\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\Esthenos\Learn\app\templates\base.html", line 40, in top-level template code
    {% block content %}{% endblock %}
  File "D:\Esthenos\Learn\app\templates\user.html", line 18, in block 'content'
    {{ form.hidden_tag() }}
  File "D:\Esthenos\Learn\venv\lib\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2023-02-28 11:10:23,114 INFO: Microblog startup [in D:\Esthenos\Learn\app\__init__.py:44]
2023-02-28 11:10:47,209 ERROR: Exception on /user/ab [GET] [in D:\Esthenos\Learn\venv\lib\site-packages\flask\app.py:1744]
Traceback (most recent call last):
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "D:\Esthenos\Learn\app\routes.py", line 31, in user
    return render_template('user.html', user=user, posts=posts)
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "D:\Esthenos\Learn\venv\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "D:\Esthenos\Learn\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\Esthenos\Learn\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\Esthenos\Learn\app\templates\base.html", line 40, in top-level template code
    {% block content %}{% endblock %}
  File "D:\Esthenos\Learn\app\templates\user.html", line 18, in block 'content'
    {{ form.hidden_tag() }}
  File "D:\Esthenos\Learn\venv\lib\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2023-02-28 11:13:28,693 INFO: Microblog startup [in D:\Esthenos\Learn\app\__init__.py:44]
2023-02-28 11:13:36,865 ERROR: Exception on / [GET] [in D:\Esthenos\Learn\venv\lib\site-packages\flask\app.py:1744]
Traceback (most recent call last):
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "D:\Esthenos\Learn\app\routes.py", line 22, in index
    form = PostForm()
NameError: name 'PostForm' is not defined
2023-02-28 11:13:46,396 ERROR: Exception on /index [GET] [in D:\Esthenos\Learn\venv\lib\site-packages\flask\app.py:1744]
Traceback (most recent call last):
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\Esthenos\Learn\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "D:\Esthenos\Learn\app\routes.py", line 22, in index
    form = PostForm()
NameError: name 'PostForm' is not defined
2023-02-28 11:15:15,613 INFO: Microblog startup [in D:\Esthenos\Learn\app\__init__.py:44]
2023-02-28 11:15:36,573 INFO: Microblog startup [in D:\Esthenos\Learn\app\__init__.py:44]
